### ISSUE TITLE
set_glyph_h_advance_func() crashes with "Segmentation fault: 11"

### ISSUE THREAD

**Issue by justvanrossum** [trufont/uharfbuzz#10]
I'm trying to figure out hot to use `set_glyph_h_advance_func()`, and I'm guessing the intended pattern would be something like

```python
import uharfbuzz as hb
import sys


with open(sys.argv[1], 'rb') as fontfile:
    fontdata = fontfile.read()

text = sys.argv[2]

face = hb.Face.create(fontdata)
font = hb.Font.create(face)
upem = face.upem

font.scale = (upem, upem)
hb.ot_font_set_funcs(font)

def myfunc(font, gid, user):
    return 500
funcs = hb.FontFuncs()
funcs.set_glyph_h_advance_func(myfunc, None)
font.funcs = funcs

buf = hb.Buffer.create()

buf.add_str(text)
buf.guess_segment_properties()

features = {"kern": True, "liga": True}
hb.shape(font, buf, features)

infos = buf.glyph_infos
positions = buf.glyph_positions

for info, pos in zip(infos, positions):
    gid = info.codepoint
    cluster = info.cluster
    x_advance = pos.x_advance
    x_offset = pos.x_offset
    y_offset = pos.y_offset
    print(f"gid{gid}={cluster}@{x_advance},{x_offset}+{y_offset}")
```
But this results in a segmentation fault at `funcs.set_glyph_h_advance_func(myfunc, None)`

**Comment by HinTak** [comment]
I have a look at harfbuzz"s gobject python-binding doc, (and shameless plug of my harfbuzz-python-demos project...), I think you need to do something like `H_func_obj=H_func(myFunc);` and pass that to the input of `set_glyph...func`. That's what the auto-generated gobject python-binding doc says (or my reading of it).

**Comment by HinTak** [comment]
Of course uharfbuzz may be clever enough to do the function object type-cast internally or auto-convert from python routine to c routine, but I doubt it :) .

**Comment by justvanrossum** [comment]
uharfbuzz is made with cython, so I think details of how this should be handled are different. I'm placing my bet on a two minute fix from @anthrotype :) I should learn cython: I really like how the code looks compared to raw C.

**Comment by HinTak** [comment]
The internals of HarBuzz is the same, and the starting point (python) is the same. The gobject binding of `set_glyph_h_advance_func` needs a function prototype cast from python to c for the 2nd argument. As in `set_glyph_h_advance_func(..., h_func_t(myFunc),...)`.  I suppose uharfbuzz can hide the protype cast, by doing something like:

```
if (typeof(myFunc) == 'python..routine'):
    myFunc = h_func_t(myFunc)
```

That's two lines for sure. Just needs the correct two-lines :-) .

**Comment by adrientetar** [comment]
You need to use `hb.FontFuncs.create()` to create the wrapped object (eg. https://github.com/trufont/trufont/blob/wx/src/trufont/objects/layoutEngine.py#L43), as is used to construct the other objects in the code you posted.

Note in the future can you post the traceback when you report something.

**Comment by justvanrossum** [comment]
Ah, thank you, that works. Well, there was no Python traceback.

Any chance that using such an object in the wrong way could not crash hard but give a proper traceback?

**Comment by justvanrossum** [comment]
A hard crash is still a bug, so I suggest to keep this issue open, or create a new one.

**Comment by khaledhosny** [comment]
Also I think it is more idiomatic Python for the constructor to return a new object, instead of having a `.create()` method.

**Comment by justvanrossum** [comment]
I'm actually fine with a non-idiomatic constructor, as long as there are safeguards to prevent using the uninitialized object.

**Comment by anthrotype** [comment]
> I think it is more idiomatic Python for the constructor to return a new object, instead of having a .create() method

I agree. We should have `__cinit__` methods do the object initialization that's currently being done in those `create` classmethods.
