### ISSUE TITLE
Higher level interface to uharfbuzz?

### ISSUE THREAD

**Issue by justvanrossum** [trufont/uharfbuzz#15]
I've been writing a more Pythonic layer on top of uharfbuzz. I would gladly contribute it (I can see it as a submodule in uharfbuzz), if people here agree this is useful.

Just posting this here to test the waters, I can gladly make a PR:

[hbShape.py.zip](https://github.com/trufont/uharfbuzz/files/2707502/hbShape.py.zip)

Perhaps as something like `uharfbuzz.shape.Shaper`.

**Comment by anthrotype** [comment]
sure, send a PR and we'll happily take a look :)

**Comment by justvanrossum** [comment]
In the meantime I learned a lot more of the niceties that uharfbuzz offers and my higher level approach needs rethinking. What I've been using myself has evolved into something that is no longer general enough. Closing this, as I currently have no interest or time to work on it.
