### ISSUE TITLE
uharfbuzz.Face.create_for_tables(...) broken?

### ISSUE THREAD

**Issue by justvanrossum** [trufont/uharfbuzz#17]
```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    face = hb.Face.create_for_tables(_get_layout_table, tables)
  File "_harfbuzz.pyx", line 271, in uharfbuzz._harfbuzz.Face.create_for_tables
  File "_harfbuzz.pyx", line 248, in uharfbuzz._harfbuzz.Face.__cinit__
TypeError: __cinit__() takes at least 1 positional argument (0 given)
```

**Comment by jenskutilek** [comment]
I noticed as much (
https://github.com/trufont/uharfbuzz/pull/12#issuecomment-459361204), but for my life can't get to compile uharfbuzz to test the fix ...

**Comment by justvanrossum** [comment]
Yeah, I hope @anthrotype will have an opportunity to look at some point.

**Comment by anthrotype** [comment]
Sorry guys, I'll be busy with internal training for another couple of weeks at least. Can you at least pin to the previous version for now?

**Comment by justvanrossum** [comment]
It's not urgent for me at all, thanks!

**Comment by jenskutilek** [comment]
I tried using a previous version, but that gives me the segfault in TruFont that Just reported here previously (#10). It’s not urgent for me either, just checking out TruFont.

**Comment by anthrotype** [comment]
This should work. Could you see if it works and send a PR?
I can't finish this right now.

```diff
diff --git a/src/uharfbuzz/_harfbuzz.pyx b/src/uharfbuzz/_harfbuzz.pyx
index 23a9fc3..9992b7f 100644
--- a/src/uharfbuzz/_harfbuzz.pyx
+++ b/src/uharfbuzz/_harfbuzz.pyx
@@ -246,9 +246,13 @@ cdef class Face:
     cdef object _reference_table_func

     def __cinit__(self, bytes blob, int index=0):
-        cdef hb_blob_t* hb_blob = hb_blob_create(
-            blob, len(blob), HB_MEMORY_MODE_READONLY, NULL, NULL)
-        self._hb_face = hb_face_create(hb_blob, index)
+        cdef hb_blob_t* hb_blob
+        if blob is not None:
+            hb_blob = hb_blob_create(
+                blob, len(blob), HB_MEMORY_MODE_READONLY, NULL, NULL)
+            self._hb_face = hb_face_create(hb_blob, index)
+        else:
+            self._hb_face = NULL

     def __dealloc__(self):
         if self._hb_face is not NULL:
@@ -268,7 +272,7 @@ cdef class Face:
                               object  # user_data
                           ], bytes],
                           user_data: object):
-        cdef Face inst = cls()
+        cdef Face inst = cls(None)
         inst._hb_face = hb_face_create_for_tables(
             _reference_table_func, <void*>user_data, NULL)
         hb_face_set_user_data(inst._hb_face, &k, <void*>inst, NULL, 0)
```

**Comment by justvanrossum** [comment]
I can't, as setting up the requirements to build uharfbuzz is too cumbersome. Also: this issue isn't blocking anything I'm working on — I just noticed the breakage. Anyone else maybe?

**Comment by anthrotype** [comment]
No problem, I can take a look next week.
Btw, to build from source you only need the C/C++ compiler toolchain for your platform. Then install the requirements-dev.txt inside a virtual environment, and run python setup.py bdist_wheel to build the wheel.

**Comment by anthrotype** [comment]
I confirm the patch above no longer crashes trufont.

@justvanrossum about building from source, I just remembered that it's actually easier than what I wrote earlier. I had already set up a `pyproject.toml` file (PEP 517/518), so basically as long as you have a recent pip version (the latest, the better), you can simply do `pip install .` or (`pip install -e .`) and all the build requirements (well, everything except the C++ compiler which your platform needs to provude!) are automatically installed in a temporary build environment.

**Comment by justvanrossum** [comment]
Thank you, I will try that!
