### ISSUE TITLE
Installing via pip fails

### ISSUE THREAD

**Issue by ralsina** [trufont/uharfbuzz#4]
Tried it in python 3.7  gives this error

```
$ pip3 install uharfbuzz                                                                           
Collecting uharfbuzz
  Downloading https://files.pythonhosted.org/packages/e6/62/e74edc052bf27cf471ef767b4b9a8f94e3b7efa27cae6951e288a438930a/uharfbuzz-0.1.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xb/nbwgxr110kbc1bphq6mqlmxc0000gq/T/pip-install-mwqnkf_p/uharfbuzz/setup.py", line 41, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'```

**Comment by anthrotype** [comment]
@ralsina thanks for the report. Installing from source is tricky. I'll try to make that work more smoothly.
Currently we only published wheels for python3.6. I'm working on building and pushing wheels for 3.7 as well.

**Comment by anthrotype** [comment]
the instructions to build from source (preferably from within a fresh virtual environment): 

```
$ git clone https://github.com/trufont/uharfbuzz
$ cd uharfbuzz
$ pip install -r requirements-dev.txt
$ pip install .
```

**Comment by ralsina** [comment]
But then you really should not upload to pypi

**Comment by ralsina** [comment]
I can confirm, that works perfectly :-)

**Comment by anthrotype** [comment]
oh, needless to say, when you install from source, you need a C/C++ compiler properly set up on your machine. What python version and operating system would you like to run this on?
Currently we only plan build/upload to PyPI precompiled wheels for python3.6 and python3.7

**Comment by ralsina** [comment]
I am doing this in a OSX machine, it seems to have one.

precompiled wheels for python >= 3.6 is more than enough, specially if you
provide windows (I assume linux people will manage)

**Comment by anthrotype** [comment]
there is a very complex build system behind this little wrapper. We are using cmake to download the harfbuzz source tarball, unpack, configure and and build (using ninja) a static libary that is then linked to the cythonized extension module. That's why I said it's tricky to build from source :)
But now thanks to pip support for PEP518 and the use of pyproject.toml where we can specify extra build requirements, this is now possible.

**Comment by anthrotype** [comment]
I just tagged v0.2.0. The wheels are building and uploading as we speak. Give the bots a few minutes then you can try to `pip install --upgrade uharfbuzz`. it should magically just work ;)

**Comment by anthrotype** [comment]
the PyPI website is also heavily cached, so it may take a while before pip sees the new uploaded files. In my experience it may take up to half an hour for the dns to update

**Comment by anthrotype** [comment]
py36.py37 wheels for Linux, Mac and Windows are now available from
https://pypi.org/project/uharfbuzz/0.2.0/#files
