### ISSUE TITLE
Finding a font

### ISSUE THREAD

**Issue by ralsina** [trufont/uharfbuzz#5]
More of a question, really, sorry about the medium :-)

In the example, you are loading the font from a file:

```
with open(sys.argv[1], 'rb') as fontfile:
    fontdata = fontfile.read()

text = sys.argv[2]

face = hb.Face.create(fontdata)
font = hb.Font.create(face)
upem = face.upem
```

How can I find the font in  the system instead? Basically I want the equivalent of this freetype-based code:

```
    font_lib = ft.get_default_lib()
    face = font_lib.find_face("Arial")
    face.set_char_size(size=1, resolution=64)
    font = hb.Font.ft_create(face)
```

**Comment by anthrotype** [comment]
well, that's not harfbuzz's job, is it?
I think you are looking for a python wrapper for the fontconfig library.

**Comment by ralsina** [comment]
Ok, just asking since it seems like a normal usage pattern, maybe you had a
way to do it.

**Comment by anthrotype** [comment]
we use these harfbuzz bindings in a font editor application so we already have the path to the font file.
Try search in pypi.org for some python bindings to fontconfig library. I haven't tried any of these I don't know what to recommend you.

E.g. there's this: https://github.com/tarruda/python-fclist

I think matplotlib has some font manager that queries the system for installed fonts.
https://matplotlib.org/api/font_manager_api.html

**Comment by ralsina** [comment]
Just for completeness and future googlers, that fclist is py2-only and seems abandoned, this fork is better:

https://github.com/MonsieurV/python-fclist
