### ISSUE TITLE
info.cluster is utf-8 index, not unicode?

### ISSUE THREAD

**Issue by justvanrossum** [trufont/uharfbuzz#9]
It appears that the info.cluster index is utf-8-based, not unicode character index, as if using `hb-shape --utf8-clusters`. Is this intentional? Intuitively I would have assumed info.cluster would be a unicode char index.

**Comment by anthrotype** [comment]
hm, you're right. Maybe we should do something similar to this, immediately after populating the buffer in `Buffer.add_str` method:

https://github.com/harfbuzz/harfbuzz/blob/1683bb2c9337fa34e5e80d459ab5eab99d7a9804/util/options.hh#L214-L224

That utf8_clusters option seems to be false by default for the hb-shape, hb-view, etc. command line tools:
https://github.com/harfbuzz/harfbuzz/blob/1683bb2c9337fa34e5e80d459ab5eab99d7a9804/util/options.hh#L155

@khaledhosny WDYT?

**Comment by khaledhosny** [comment]
The simplest way is to feed HarfBuzz UTF-32 code units instead of UTF-8 ones, basically something like [this](https://github.com/harfbuzz/harfbuzz/blob/1683bb2c9337fa34e5e80d459ab5eab99d7a9804/src/sample.py#L49-L61), then the clusters will be UTF-32 indices (or UTF-16 for narrow Python 2 builds, if you care for that) which will match Python’s text indices.

**Comment by khaledhosny** [comment]
Basically just replace `text.encode('UTF-8')` with `array.array('I', text.encode('utf-32'))[1:]` and use `hb_buffer_add_utt32`. This also affects `item_offset` and `item_length` as these expect code units length (UTF-8 in your current code) not code point length:
https://github.com/trufont/uharfbuzz/blob/3e8a1e288ea780f3edc6802fe5e30d1c041420bc/src/uharfbuzz/_harfbuzz.pyx#L165-L175

**Comment by khaledhosny** [comment]
For an immediate work around, @justvanrossum can use `add_codepoints` instead of `add_str` (the code points input would be something like `[ord(c) for c in text]`).
